version: "3"
  services:
  jenkins:
    container_name: jenkins
    environment: 
      -
    image: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    volumes: 
      - nginx-log:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - jenkins-net
    restart: always
volumes:
jenkins-log:
jenkins-data:
networks:
jenkins-net: